server:
  port: 8002
  servlet:
    context-path: /gramtu/web
spring:
  application:
    name: gratu-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gramtu?allowMultiQueries=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: 123456a?
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: yfdev
    password: yfdev
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    # 最大空闲数
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 200
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制） 默认 -1
        max-wait: 1000
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
      shutdown-timeout: 20000
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
fdfs:
  # 读取超时
  so-timeout: 2000
  # 连接超时
  connect-timeout: 2000
  # 生成缩略图
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 127.0.0.1:22122
logging:
  file:
    name: /home/gramtu/logs/gramtu-web.log